openapi: 3.1.0
info:
  title: ECS Service Deployment
  version: 26.1.0
servers:
  - url: ''
paths:
  /v1/tasks/{task}:
    get:
      tags:
        - Tasks
      summary: GET /v1/tasks/{task}
      operationId: get_task
      parameters:
        - required: true
          schema:
            type: string
            title: Task
          name: task
          in: path
      responses:
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '200':
          description: OK
          content:
            application/json: {}
        '202':
          description: Accepted
          content:
            application/json: {}
        '401':
          description: Unauthorized
          content:
            application/json: {}
        '404':
          description: Not Found
          content:
            application/json: {}
        '417':
          description: Expectation Failed
          content:
            application/json:
              schema:
                properties:
                  error:
                    anyOf:
                      - type: string
                      - items: {}
                        type: array
                    title: Error
                type: object
                required:
                  - error
                title: ErrorResponse
      security:
        - ApiKeyAuth: []
    patch:
      tags:
        - Tasks
      summary: Update an ECS scheduled task.
      description: Update an ECS scheduled task.
      operationId: patch_task
      parameters:
        - required: true
          schema:
            type: string
            title: Task
          name: task
          in: path
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskDeploymentRequest'
        required: true
      responses:
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '200':
          description: OK
          content:
            application/json: {}
        '401':
          description: Unauthorized
          content:
            application/json: {}
        '202':
          description: Accepted
          content:
            application/json: {}
        '417':
          description: Expectation Failed
          content:
            application/json: {}
      security:
        - ApiKeyAuth: []
  /v1/services/{service}:
    get:
      tags:
        - Services
      summary: GET /v1/services/{service}
      operationId: get_service
      parameters:
        - required: true
          schema:
            type: string
            title: Service
          name: service
          in: path
      responses:
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '200':
          description: OK
          content:
            application/json: {}
        '202':
          description: Accepted
          content:
            application/json: {}
        '401':
          description: Unauthorized
          content:
            application/json: {}
        '404':
          description: Not Found
          content:
            application/json: {}
        '417':
          description: Expectation Failed
          content:
            application/json: {}
      security:
        - ApiKeyAuth: []
    patch:
      tags:
        - Services
      summary: Update an ECS service.
      description: Update an ECS service.
      operationId: patch_service
      parameters:
        - required: true
          schema:
            type: string
            title: Service
          name: service
          in: path
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceDeploymentRequest'
        required: true
      responses:
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '200':
          description: OK
          content:
            application/json: {}
        '401':
          description: Unauthorized
          content:
            application/json: {}
        '202':
          description: Accepted
          content:
            application/json: {}
        '417':
          description: Expectation Failed
          content:
            application/json: {}
      security:
        - ApiKeyAuth: []
  /v1/tasks:
    get:
      tags:
        - Tasks
      summary: Get available ECS tasks.
      description: Get available ECS tasks.
      operationId: get_tasks
      responses:
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '200':
          description: OK
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
                example:
                  - task-a
                  - task-b
        '401':
          description: Unauthorized
          content:
            application/json: {}
      security:
        - ApiKeyAuth: []
  /v1/services:
    get:
      tags:
        - Services
      summary: Get available ECS services.
      description: Get available ECS services.
      operationId: get_services
      responses:
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '200':
          description: OK
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
                example:
                  - service-a
                  - service-b
        '401':
          description: Unauthorized
          content:
            application/json: {}
      security:
        - ApiKeyAuth: []
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ServiceDeploymentRequest:
      properties:
        image:
          type: string
          minLength: 1
          title: Image
          description: The container image to use for the service
        force:
          anyOf:
            - type: boolean
            - type: 'null'
          title: Force
          description: Force deployment of same image
          default: false
        secret_arns:
          anyOf:
            - items:
                type: string
                pattern: arn:aws:secretsmanager:[a-z0-9-]+:[0-9]+:secret:.*
              type: array
            - type: 'null'
          title: Secret Arns
          description: List of secret ARNs to attach to the service
          default: []
      type: object
      required:
        - image
      title: ServiceDeploymentRequest
      description: ECS Service Deployment Request.
    TaskDeploymentRequest:
      properties:
        image:
          type: string
          minLength: 1
          title: Image
          description: The container image to use for the service
      type: object
      required:
        - image
      title: TaskDeploymentRequest
      description: 'ECS Task Deployment Request.

        Triggered by either scheduled or event pattern.'
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
    ResponseValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: ResponseValidationError
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-token
