[project]
name = "maws"
version = "26.1.0"
description = "Managed AWS command line client"
authors = [
  { name = "Jochen Werner", email = "jochen.werner@skaylink.com" },
  { name = "Stefan Heitmüller", email = "stefan.heitmueller@skaylink.com" },
]
requires-python = ">=3.12"
readme = "README.md"
dependencies = [
  "pydantic==2.12.5",
  "pydantic-settings==2.13.1",
  "typer==0.24.0",
  "rich==14.3.3",
  "openapi-python-client==0.28.3",
  "mypy-extensions==1.1.0",
  "pathspec==1.0.4",
]

[project.urls]
Repository = "https://github.com/skaylink/maws"

[project.scripts]
maws = "maws.main:main"

[dependency-groups]
dev = [
  "faker==40.11.1",
  "pytest==9.0.2",
  "pytest-env==1.6.0",
  "pytest-cov==7.1.0",
]
build = [
  "nuitka==4.0",
]

[tool.uv]
default-groups = ["dev"]

[build-system]
requires = ["uv_build>=0.9.6,<0.11.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "maws"

[tool.pytest_env]
ENDPOINT = "http://dummy-host"
SECRET = "dummy-cmapi-secret"

[tool.pytest.ini_options]
filterwarnings = ["ignore::DeprecationWarning"]
addopts = """-vv"""

[tool.coverage.run]
omit = ["tests/*", "src/maws/clients/*"]

[tool.black]
line-length = 120
