---
# yamllint disable rule:line-length
name: release

# yamllint disable rule:truthy
on:
  release:
    types:
      - published

jobs:
  exe:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup mise runtime manager
        uses: jdx/mise-action@v2
        with:
          install: false
          cache: false
          experimental: true
      - name: Install mise toolchain
        run: mise install
      - name: Build exe
        run: mise build:exe
        env:
          DEBUG: ${{ runner.debug }}
      - name: Release assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/maws.exe
          fail_on_unmatched_files: true
  binary:
    runs-on: ${{ matrix.arch.runner }}
    env:
      DEBIAN_FRONTEND: noninteractive
    strategy:
      matrix:
        arch:
          - name: x86_64
            runner: ubuntu-24.04
          - name: aarch64
            runner: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup mise runtime manager
        uses: jdx/mise-action@v2
        with:
          install: false
          cache: false
          experimental: true
      - name: Install mise toolchain
        run: mise install
      - name: Build binary for ${{ matrix.arch.name }}
        run: mise build:binary
        env:
          DEBUG: ${{ runner.debug }}
      - name: Release assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/linux/*/maws_*
          fail_on_unmatched_files: true
